# SPDX-FileCopyrightText: Lukas Sommer <sommerluk@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR MIT





# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1





# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:

  job-build-bigendian:
    machine:
      image: ubuntu-2204:current
    steps:
      # See: https://circleci.com/docs/configuration-reference/#steps
      - checkout
      - run:
          name: Enable run containers with different architectures
          command: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Run docker container for s390x
          command: docker run -it -d --platform linux/s390x --name ubuntu_bigendian ubuntu:22.04
      - run:
          name: Display information about the container’s virtual hardware
          command: |
            docker exec -it ubuntu_bigendian bash -c "lscpu"
            echo RAM in Mebibyte
            free --total --mebi
      - run:
          name: Set noninteractive environment
          command: docker exec -it ubuntu_bigendian bash -c "echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV"
      - run:
          name: Checkout code into the virtual machine
          command: |
            docker cp "$(pwd)" ubuntu_bigendian:/project
      - run:
          name: Install dependencies
          command: |
            docker exec -it ubuntu_bigendian bash -c "apt-get update --assume-yes"
            docker exec -it ubuntu_bigendian bash -c "apt-get install --assume-yes --no-install-recommends make clang "
      - run:
          name: Build project
          command: |
            docker exec -it ubuntu_bigendian bash -c '(
                set -ex
                cd /project
                PARALLEL_PROCESSES=`nproc --all`
                ./configure
                make
                make check
              )'





# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  workflow-build:
    jobs:
      - job-build-bigendian:
